[build]
  # Directorio de publicación (donde está el HTML principal)
  publish = "."
  
  # Comando de build (no necesario para HTML estático)
  command = "echo 'No build required'"

[functions]
  # Directorio de las funciones
  directory = "netlify/functions"
  
  # Runtime de Node.js
  node_bundler = "esbuild"

# Configuración de headers para CORS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"

# Configuración de cache para archivos estáticos
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Variables de entorno (configurar en el panel de Netlify)
# [build.environment]
#   GROQ_API_KEY = "tu_clave_aqui"